### ISSUE TITLE
issue with jpg file

### ISSUE THREAD

**Issue by shirish075** [prasad924/Image-Steganography#2]
"Only PNG files can be encoded and decoded, but JPG files are not supported."

**Comment by prasad924** [comment]
JPG files, due to their lossy compression nature, are unsuitable for our traditional image steganography. However, for your clarification, techniques like using the Discrete Cosine Transform (DCT) allow for embedding data in JPG files effectively by hiding information within the image's frequency components, minimizing visible changes to the image's quality.

**Comment by shirish075** [comment]
try to add this info in readme because i spent alot of time figuring out there is an issue with jpg thanks
